version: "3.9"

services:
  web:
    build: .
    image: v0teforpedro/web_service:latest
    container_name: web_service
    command: gunicorn config.wsgi:application --workers 4 --bind 0.0.0.0:8090
    volumes:
      - static_volume:/opt/src/static
      - media_volume:/opt/src/media
    ports:
      - "8090:8090"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    container_name: db_service
    volumes:
      - db_data_volume:/var/lib/postgresql/data/
    ports:
      - "5438:5432"
    env_file:
      - .env

  nginx:
    build: ./nginx
    image: v0teforpedro/nginx_service:latest
    container_name: nginx_service
    volumes:
      - static_volume:/opt/src/static
      - media_volume:/opt/src/media
    ports:
      - "80:80"
    depends_on:
      - db

volumes:
  db_data_volume:
    name: db_data
  static_volume:
    name: static_data
  media_volume:
    name: media_data
  src_volume:
    name: source_code